IHM Segment SOL: CameraWidget Class Reference
CameraWidget Class Reference
#include "camerawidget.h"
Public Member Functions
CameraWidget (QWidget *parent=0)
Constructeur.
~CameraWidget (void)
Destructeur.
QPixmap toPixmap (IplImage *)
Conversion d'image.
void putFrame (IplImage *)
Placement d'image.
Private Attributes
QLabel * m_imageLabel
QVBoxLayout * m_layout
QImage m_image
Detailed Description
Definition at line 21 of file camerawidget.h.
Constructor & Destructor Documentation
CameraWidget::CameraWidget (QWidget * parent = 0)
Constructeur.
Placement du label dans un layout.
Parameters
QWidget *parent
Definition at line 17 of file camerawidget.cpp.
References m_image, m_imageLabel, and m_layout.
    : QWidget(parent)
{
    m_layout = new QVBoxLayout;
    m_imageLabel = new QLabel;
    QImage dummy(100, 100, QImage::Format_RGB32);
    m_image = dummy;
    m_layout->addWidget(m_imageLabel);
    for (int x = 0; x < 100; x ++)
        for (int y =0; y < 100; y++)
            m_image.setPixel(x,y,qRgb(x, y, y));
    m_imageLabel->setPixmap(QPixmap::fromImage(m_image));
    setLayout(m_layout);
}
CameraWidget::~CameraWidget (void)
Destructeur.
Parameters
void
Definition at line 42 of file camerawidget.cpp.
{
}
Member Function Documentation
void CameraWidget::putFrame (IplImage * image)
Placement d'image.
Fonction qui permet le placement de l'image dans le label destiné à l'accueillir
Parameters
IplImage *image
Definition at line 53 of file camerawidget.cpp.
References m_imageLabel, and toPixmap().
Referenced by MainWindow::timerEvent().
{
    m_imageLabel->setPixmap(toPixmap(image));
}
QPixmap CameraWidget::toPixmap (IplImage * cvimage)
Conversion d'image.
Fonction de conversion d'une IplImage en une QPixmap
Parameters
IplImage *cvimage
Returns
QPixmap
Definition at line 65 of file camerawidget.cpp.
References m_image.
Referenced by putFrame(), and MainWindow::savePicture().
{
    int cvIndex, cvLineStart;
    switch (cvimage->depth) {
        case IPL_DEPTH_8U:
            switch (cvimage->nChannels) {
                case 3:
                    if ( (cvimage->width != m_image.width()) || (cvimage->height != m_image.height()) ) {
                        QImage temp(cvimage->width, cvimage->height, QImage::Format_RGB32);
                        m_image = temp;
                    }
                    cvIndex = 0; cvLineStart = 0;
                    for (int y = 0; y < cvimage->height; y++) {
                        unsigned char red,green,blue;
                        cvIndex = cvLineStart;
                        for (int x = 0; x < cvimage->width; x++) {
                            red = cvimage->imageData[cvIndex+2];
                            green = cvimage->imageData[cvIndex+1];
                            blue = cvimage->imageData[cvIndex+0];
                            m_image.setPixel(x,y,qRgb(red, green, blue));
                            cvIndex += 3;
                        }
                        cvLineStart += cvimage->widthStep;
                    }
                    break;
            case 1:
                if ( (cvimage->width != m_image.width()) || (cvimage->height != m_image.height()) ) {
                    QImage temp(cvimage->width, cvimage->height, QImage::Format_RGB32);
                    m_image = temp;
                }
                cvIndex = 0; cvLineStart = 0;
                for (int y = 0; y < cvimage->height; y++) {
                    unsigned char red,green,blue;
                    cvIndex = cvLineStart;
                    for (int x = 0; x < cvimage->width; x++) {
                        red = cvimage->imageData[cvIndex+2];
                        green = cvimage->imageData[cvIndex+1];
                        blue = cvimage->imageData[cvIndex+0];
                        m_image.setPixel(x,y,qRgb(red, green, blue));
                        cvIndex += 3;
                    }
                    cvLineStart += cvimage->widthStep;
                }
                break;
                default:
                    qWarning("This number of channels is not supported\n");
                    break;
            }
            break;
        default:
            qWarning("This type of IplImage is not implemented in QOpenCVWidget\n");
            break;
    }
    return QPixmap::fromImage(m_image);
}
Member Data Documentation
QImage CameraWidget::m_image private
Definition at line 33 of file camerawidget.h.
Referenced by CameraWidget(), and toPixmap().
QLabel* CameraWidget::m_imageLabel private
Definition at line 31 of file camerawidget.h.
Referenced by CameraWidget(), and putFrame().
QVBoxLayout* CameraWidget::m_layout private
Definition at line 32 of file camerawidget.h.
Referenced by CameraWidget().
The documentation for this class was generated from the following files:
camerawidget.h
camerawidget.cpp