IHM Segment SOL: qAttitudeIndicator Class Reference
qAttitudeIndicator Class Reference
#include "qattitudeindicator.h"
Public Member Functions
qAttitudeIndicator (QWidget *parent=0)
~qAttitudeIndicator ()
void setRoll (qreal val)
void setPitch (qreal val)
qreal getRoll ()
qreal getPitch ()
void doHorizon ()
Public Attributes
qreal roll
qreal pitch
Protected Member Functions
void paintEvent (QPaintEvent *event)
void resizeEvent (QResizeEvent *event)
Private Member Functions
void getRollLine (EN_TYPES_ATTITUDE type, QPoint *pFrom, QPoint *pTo)
void getPitchLine (EN_TYPES_ATTITUDE type, quint32 index, QPoint *pFrom, QPoint *pTo)
void initTargetChar ()
void resizeTargetChar ()
void initRollChar ()
void resizeRollChar ()
Private Attributes
int size
QPoint rollPoint [numbRollLine][2]
qreal rollRotate [numbRollLine]
QPoint pitchPoint [numbPitchLine][2]
QVector< QLine > target
QVector< QLine > rollPointer
Detailed Description
Definition at line 23 of file qattitudeindicator.h.
Constructor & Destructor Documentation
qAttitudeIndicator::qAttitudeIndicator (QWidget * parent = 0)
Definition at line 17 of file qattitudeindicator.cpp.
References defaultsRollRotate, defaultsTypePitch, defaultsTypeRoll, getPitchLine(), getRollLine(), initRollChar(), initTargetChar(), numbPitchLine, numbRollLine, pitch, pitchPoint, roll, rollPoint, rollRotate, size, sizeMax, and sizeMin.
    : QWidget(parent)
{
    //QTimer *timer = new QTimer(this);
    //connect(timer, SIGNAL(timeout()), this, SLOT(update()));
    //connect(timer, SIGNAL(timeout()), this, SLOT(nunchuckEvent()));
    //timer->start(50);
    //startTimer(50);
    size = sizeMin;
    setMinimumSize(sizeMin,sizeMin);
    setMaximumSize(sizeMax,sizeMax);
    resize(size, size);
    // from 0 degrees;
    for(int i=0;i < numbRollLine;i++)
    {
        rollRotate[i] = defaultsRollRotate[i];
        getRollLine(defaultsTypeRoll[i],&rollPoint[i][0],&rollPoint[i][1]);
    }
    for(int i=0;i< numbPitchLine;i++)
        getPitchLine(defaultsTypePitch[i],i,&pitchPoint[i][0],&pitchPoint[i][1]);
    initTargetChar();
    initRollChar();
    roll = 0.0;
    pitch = 0.0;
    //wiiTest = new Nunchuck(PARAM_DRONE);
}
qAttitudeIndicator::~qAttitudeIndicator ()
Definition at line 48 of file qattitudeindicator.cpp.
{
    //delete wiiTest;
}
Member Function Documentation
void qAttitudeIndicator::doHorizon ()
Definition at line 121 of file qattitudeindicator.cpp.
Referenced by QTh_Base::run(), and QBase::run().
{
    update();
}
qreal qAttitudeIndicator::getPitch () inline
Definition at line 33 of file qattitudeindicator.h.
References pitch.
{return pitch;}
void qAttitudeIndicator::getPitchLine (EN_TYPES_ATTITUDE type, quint32 index, QPoint * pFrom, QPoint * pTo) private
Definition at line 98 of file qattitudeindicator.cpp.
References size, and smallPitchLine.
Referenced by qAttitudeIndicator(), and resizeEvent().
{
    int x,y;
    if(index>=4) index++;
    y = size*(0.25-index*0.0625);
    x = (type==smallPitchLine)? (3*size/32):(5*size/32);
    pFrom->setX(-x);
    pFrom->setY(y);
    pTo->setX(x);
    pTo->setY(y);
}
qreal qAttitudeIndicator::getRoll () inline
Definition at line 32 of file qattitudeindicator.h.
References roll.
{return roll;}
void qAttitudeIndicator::getRollLine (EN_TYPES_ATTITUDE type, QPoint * pFrom, QPoint * pTo) private
Definition at line 89 of file qattitudeindicator.cpp.
References size, and smallRollLine.
Referenced by qAttitudeIndicator(), and resizeEvent().
{
    quint8 ofs = (type == smallRollLine)? (size/40) : (size/20) ;
    pFrom->setY(size/2-ofs);
    pFrom->setX(0);
    pTo->setY(size/2);
    pTo->setX(0);
}
void qAttitudeIndicator::initRollChar () private
Definition at line 72 of file qattitudeindicator.cpp.
References size, and target.
Referenced by qAttitudeIndicator(), and resizeRollChar().
{
    QLine line;
    line.setLine(-size/32,14*size/32,0,15*size/32);
    target.append(line);
    line.setLine(0,15*size/32,size/32,14*size/32);
    target.append(line);
    line.setLine(size/32,14*size/32,-size/32,14*size/32);
    target.append(line);
}
void qAttitudeIndicator::initTargetChar () private
Definition at line 53 of file qattitudeindicator.cpp.
References size, and target.
Referenced by qAttitudeIndicator(), and resizeTargetChar().
{
    QLine line;
    line.setLine(-size/4,0,-size/16,0);
    target.append(line);
    line.setLine(-size/16,0,0,-size/32);
    target.append(line);
    line.setLine(0,-size/32,size/16,0);
    target.append(line);
    line.setLine(size/16,0,size/4,0);
    target.append(line);
}
void qAttitudeIndicator::paintEvent (QPaintEvent * event) protected
Definition at line 126 of file qattitudeindicator.cpp.
References numbPitchLine, numbRollLine, pitch, pitchPoint, roll, rollPoint, rollPointer, rollRotate, size, and target.
{
    QPainter painter(this);
    QPoint center(0,0);
    QPen whitePen(Qt::white);
    QPen blackPen(Qt::black);
    QBrush bgSky(QColor(48,172,220));
    QBrush bgGround(QColor(247,168,21));
    whitePen.setWidth(2);
    blackPen.setWidth(1);
    painter.setRenderHint(QPainter::Antialiasing);
    painter.translate(width() / 2, height() / 2);
    int side = qMin(width(), height());
    painter.scale(side / (qreal)(size), side / (qreal)(size));
    painter.setPen(blackPen);
    painter.rotate(roll);
    painter.setBrush(bgSky);
    int y = 0.25*size*pitch/20.;
    int x = sqrt(size*size/4 - y*y);
    qreal gr = atan((double)(y)/x);
    gr = gr * 180./3.1415926;
    painter.drawChord(-side/2,-side/2,side,side,gr*16,(180-2*gr)*16);
    painter.setBrush(bgGround);
    painter.drawChord(-side/2,-side/2,side,side,gr*16,-(180+2*gr)*16);
    painter.setPen(whitePen);
    painter.drawLine(-x,-y,x,-y);
    painter.setPen(blackPen);
    painter.rotate(-180.);
    for(int i=0;i<numbRollLine;i++)
    {
        painter.rotate(rollRotate[i]);
        painter.drawLine(rollPoint[i][0],rollPoint[i][1]);
    }
    whitePen.setWidth(1);
    painter.setPen(whitePen);
    painter.rotate(-90.);
    for(int i=0;i<numbPitchLine;i++)
    {
        painter.drawLine(pitchPoint[i][0],pitchPoint[i][1]);
    }
    painter.rotate(-roll);
    blackPen.setWidth(3);
    painter.setPen(blackPen);
    painter.drawLines(target);
    painter.drawLines(rollPointer);
}
void qAttitudeIndicator::resizeEvent (QResizeEvent * event) protected
Definition at line 110 of file qattitudeindicator.cpp.
References defaultsTypePitch, defaultsTypeRoll, getPitchLine(), getRollLine(), numbPitchLine, numbRollLine, pitchPoint, resizeRollChar(), resizeTargetChar(), rollPoint, and size.
{
    size = qMin(width(),height());
    for(int i=0;i < numbRollLine;i++)
        getRollLine(defaultsTypeRoll[i],&rollPoint[i][0],&rollPoint[i][1]);
    for(int i=0;i< numbPitchLine;i++)
        getPitchLine(defaultsTypePitch[i],i,&pitchPoint[i][0],&pitchPoint[i][1]);
    resizeTargetChar();
    resizeRollChar();
}
void qAttitudeIndicator::resizeRollChar () private
Definition at line 83 of file qattitudeindicator.cpp.
References initRollChar(), and rollPointer.
Referenced by resizeEvent().
{
    rollPointer.clear();
    initRollChar();
}
void qAttitudeIndicator::resizeTargetChar () private
Definition at line 66 of file qattitudeindicator.cpp.
References initTargetChar(), and target.
Referenced by resizeEvent().
{
    target.clear();
    initTargetChar();
}
void qAttitudeIndicator::setPitch (qreal val) inline
Definition at line 31 of file qattitudeindicator.h.
References pitch.
{pitch = val;}
void qAttitudeIndicator::setRoll (qreal val) inline
Definition at line 30 of file qattitudeindicator.h.
References roll.
{roll  = val;}
Member Data Documentation
qreal qAttitudeIndicator::pitch
Definition at line 39 of file qattitudeindicator.h.
Referenced by getPitch(), paintEvent(), qAttitudeIndicator(), QBase::run(), and setPitch().
QPoint qAttitudeIndicator::pitchPoint[numbPitchLine][2] private
Definition at line 57 of file qattitudeindicator.h.
Referenced by paintEvent(), qAttitudeIndicator(), and resizeEvent().
qreal qAttitudeIndicator::roll
Definition at line 38 of file qattitudeindicator.h.
Referenced by getRoll(), paintEvent(), qAttitudeIndicator(), QBase::run(), and setRoll().
QPoint qAttitudeIndicator::rollPoint[numbRollLine][2] private
Definition at line 55 of file qattitudeindicator.h.
Referenced by paintEvent(), qAttitudeIndicator(), and resizeEvent().
QVector<QLine> qAttitudeIndicator::rollPointer private
Definition at line 59 of file qattitudeindicator.h.
Referenced by paintEvent(), and resizeRollChar().
qreal qAttitudeIndicator::rollRotate[numbRollLine] private
Definition at line 56 of file qattitudeindicator.h.
Referenced by paintEvent(), and qAttitudeIndicator().
int qAttitudeIndicator::size private
Definition at line 54 of file qattitudeindicator.h.
Referenced by getPitchLine(), getRollLine(), initRollChar(), initTargetChar(), paintEvent(), qAttitudeIndicator(), and resizeEvent().
QVector<QLine> qAttitudeIndicator::target private
Definition at line 58 of file qattitudeindicator.h.
Referenced by initRollChar(), initTargetChar(), paintEvent(), and resizeTargetChar().
The documentation for this class was generated from the following files:
qattitudeindicator.h
qattitudeindicator.cpp