IHM Segment SOL: SlippyMap Class Reference
SlippyMap Class Reference
#include "slippymap.h"
Signals
void updated (const QRect &rect)
Public Member Functions
SlippyMap (QObject *parent=0)
void invalidate ()
void render (QPainter *p, const QRect &rect)
void pan (const QPoint &delta)
Public Attributes
int width
int height
int zoom
qreal latitude
qreal longitude
Protected Member Functions
QRect tileRect (const QPoint &tp)
Private Slots
void handleNetworkData (QNetworkReply *reply)
void download ()
Private Attributes
QPoint m_offset
QRect m_tilesRect
QPixmap m_emptyTile
QHash< QPoint, QPixmap > m_tilePixmaps
QNetworkAccessManager m_manager
QUrl m_url
Detailed Description
Definition at line 11 of file slippymap.h.
Constructor & Destructor Documentation
SlippyMap::SlippyMap (QObject * parent = 0)
Definition at line 43 of file slippymap.cpp.
References handleNetworkData(), m_emptyTile, m_manager, and tdim.
    : QObject(parent), width(400), height(300), zoom(15),
      latitude(59.9138204), longitude(10.7387413)
{
    m_emptyTile = QPixmap(tdim, tdim);
    m_emptyTile.fill(Qt::lightGray);
    QNetworkDiskCache *cache = new QNetworkDiskCache;
    cache->setCacheDirectory(QDesktopServices::storageLocation
                                (QDesktopServices::CacheLocation));
    m_manager.setCache(cache);
    connect(&m_manager, SIGNAL(finished(QNetworkReply*)),
            this, SLOT(handleNetworkData(QNetworkReply*)));
}
Member Function Documentation
void SlippyMap::download () private slot
Definition at line 160 of file slippymap.cpp.
References m_manager, m_tilePixmaps, m_tilesRect, m_url, and zoom.
Referenced by handleNetworkData(), and invalidate().
{
    QPoint grab(0, 0);
    for (int x = 0; x <= m_tilesRect.width(); ++x)
        for (int y = 0; y <= m_tilesRect.height(); ++y) {
            QPoint tp = m_tilesRect.topLeft() + QPoint(x, y);
            if (!m_tilePixmaps.contains(tp)) {
                grab = tp;
                break;
            }
        }
    if (grab == QPoint(0, 0)) {
        m_url = QUrl();
        return;
    }
    QString path = "http://tile.openstreetmap.org/%1/%2/%3.png";
    m_url = QUrl(path.arg(zoom).arg(grab.x()).arg(grab.y()));
    QNetworkRequest request;
    request.setUrl(m_url);
    request.setRawHeader("User-Agent", "Nokia (Qt) Graphics Dojo 1.0");
    request.setAttribute(QNetworkRequest::User, QVariant(grab));
    m_manager.get(request);
}
void SlippyMap::handleNetworkData (QNetworkReply * reply) private slot
Definition at line 137 of file slippymap.cpp.
References download(), m_emptyTile, m_tilePixmaps, m_tilesRect, tileRect(), and updated().
Referenced by SlippyMap().
{
    QImage img;
    QPoint tp = reply->request().attribute(QNetworkRequest::User).toPoint();
    QUrl url = reply->url();
    if (!reply->error())
        if (!img.load(reply, 0))
            img = QImage();
    reply->deleteLater();
    m_tilePixmaps[tp] = QPixmap::fromImage(img);
    if (img.isNull())
        m_tilePixmaps[tp] = m_emptyTile;
    emit updated(tileRect(tp));
    // purge unused spaces
    QRect bound = m_tilesRect.adjusted(-2, -2, 2, 2);
    foreach(QPoint tp, m_tilePixmaps.keys())
    if (!bound.contains(tp))
        m_tilePixmaps.remove(tp);
    download();
}
void SlippyMap::invalidate ()
Definition at line 58 of file slippymap.cpp.
References download(), height, latitude, longitude, m_offset, m_tilesRect, m_url, tdim, tileForCoordinate(), updated(), width, and zoom.
Referenced by LightMaps::activateZoom(), pan(), LightMaps::resizeEvent(), and LightMaps::setCenter().
{
    if (width <= 0 || height <= 0)
        return;
    QPointF ct = tileForCoordinate(latitude, longitude, zoom);
    qreal tx = ct.x();
    qreal ty = ct.y();
    // top-left corner of the center tile
    int xp = width / 2 - (tx - floor(tx)) * tdim;
    int yp = height / 2 - (ty - floor(ty)) * tdim;
    // first tile vertical and horizontal
    int xa = (xp + tdim - 1) / tdim;
    int ya = (yp + tdim - 1) / tdim;
    int xs = static_cast<int>(tx) - xa;
    int ys = static_cast<int>(ty) - ya;
    // offset for top-left tile
    m_offset = QPoint(xp - xa * tdim, yp - ya * tdim);
    // last tile vertical and horizontal
    int xe = static_cast<int>(tx) + (width - xp - 1) / tdim;
    int ye = static_cast<int>(ty) + (height - yp - 1) / tdim;
    // build a rect
    m_tilesRect = QRect(xs, ys, xe - xs + 1, ye - ys + 1);
    if (m_url.isEmpty())
        download();
    emit updated(QRect(0, 0, width, height));
}
void SlippyMap::pan (const QPoint & delta)
Definition at line 128 of file slippymap.cpp.
References invalidate(), latitude, latitudeFromTile(), longitude, longitudeFromTile(), tdim, tileForCoordinate(), and zoom.
Referenced by LightMaps::keyPressEvent(), and LightMaps::mouseMoveEvent().
{
    QPointF dx = QPointF(delta) / qreal(tdim);
    QPointF center = tileForCoordinate(latitude, longitude, zoom) - dx;
    latitude = latitudeFromTile(center.y(), zoom);
    longitude = longitudeFromTile(center.x(), zoom);
    invalidate();
}
void SlippyMap::render (QPainter * p, const QRect & rect)
Definition at line 93 of file slippymap.cpp.
References latitude, longitude, m_emptyTile, m_tilePixmaps, m_tilesRect, tileForCoordinate(), tileRect(), and zoom.
Referenced by LightMaps::paintEvent().
{
    int mx = 0, my = 0; // x and y for marker
    qreal latdiff = 0, lngdiff = 0; // storing reminder
    QPointF center = tileForCoordinate(latitude, longitude, zoom); // getting tile points for real gps point
    int cx = qFloor(center.x());
    int cy = qFloor(center.y());
    for (int x = 0; x <= m_tilesRect.width(); ++x)
        for (int y = 0; y <= m_tilesRect.height(); ++y) {
            QPoint tp(x + m_tilesRect.left(), y + m_tilesRect.top());
            QRect box = tileRect(tp);
            if (tp.x() == cx && tp.y() == cy) {
            mx = box.x();
            my = box.y();
            latdiff = qAbs(tp.x() - center.x());
            lngdiff = qAbs(tp.y() - center.y());
            }
            if (rect.intersects(box)) {
                if (m_tilePixmaps.contains(tp))
                    p->drawPixmap(box, m_tilePixmaps.value(tp));
                else
                    p->drawPixmap(box, m_emptyTile);
            }
        }
    // marker
    if (mx != 0 && my != 0) {
    QIcon marker = QIcon("/home/Guillaume_Pierre/GPS/quadcopter-24.png");
    p->drawPixmap((mx+(latdiff*256.0)-24), (my+(lngdiff*256.0)-24), marker.pixmap(24,24));
    }
}
QRect SlippyMap::tileRect (const QPoint & tp) protected
Definition at line 185 of file slippymap.cpp.
References m_offset, m_tilesRect, and tdim.
Referenced by handleNetworkData(), and render().
{
    QPoint t = tp - m_tilesRect.topLeft();
    int x = t.x() * tdim + m_offset.x();
    int y = t.y() * tdim + m_offset.y();
    return QRect(x, y, tdim, tdim);
}
void SlippyMap::updated (const QRect & rect) signal
Referenced by handleNetworkData(), and invalidate().
Member Data Documentation
int SlippyMap::height
Definition at line 22 of file slippymap.h.
Referenced by LightMaps::activateZoom(), invalidate(), and LightMaps::resizeEvent().
qreal SlippyMap::latitude
Definition at line 24 of file slippymap.h.
Referenced by LightMaps::activateZoom(), invalidate(), pan(), render(), and LightMaps::setCenter().
qreal SlippyMap::longitude
Definition at line 25 of file slippymap.h.
Referenced by LightMaps::activateZoom(), invalidate(), pan(), render(), and LightMaps::setCenter().
QPixmap SlippyMap::m_emptyTile private
Definition at line 40 of file slippymap.h.
Referenced by handleNetworkData(), render(), and SlippyMap().
QNetworkAccessManager SlippyMap::m_manager private
Definition at line 42 of file slippymap.h.
Referenced by download(), and SlippyMap().
QPoint SlippyMap::m_offset private
Definition at line 38 of file slippymap.h.
Referenced by invalidate(), and tileRect().
QHash<QPoint, QPixmap> SlippyMap::m_tilePixmaps private
Definition at line 41 of file slippymap.h.
Referenced by download(), handleNetworkData(), and render().
QRect SlippyMap::m_tilesRect private
Definition at line 39 of file slippymap.h.
Referenced by download(), handleNetworkData(), invalidate(), render(), and tileRect().
QUrl SlippyMap::m_url private
Definition at line 43 of file slippymap.h.
Referenced by download(), and invalidate().
int SlippyMap::width
Definition at line 21 of file slippymap.h.
Referenced by LightMaps::activateZoom(), invalidate(), and LightMaps::resizeEvent().
int SlippyMap::zoom
Definition at line 23 of file slippymap.h.
Referenced by LightMaps::activateZoom(), download(), invalidate(), pan(), and render().
The documentation for this class was generated from the following files:
slippymap.h
slippymap.cpp