IHM Segment SOL: Uart Class Reference
Uart Class Reference
#include "uart.h"
Public Member Functions
Uart ()
~Uart ()
Public Attributes
bool bInitialize
Protected Member Functions
bool Serial_Close ()
bool Serial_Open (const char *serial_Name, speed_t baudrate)
int Serial_Read (char *buff, int len)
int Serial_Send (char *string, int len)
Protected Attributes
char cSendBuff [12]
char cRecevBuff [12]
Private Attributes
int fd
Detailed Description
Definition at line 21 of file uart.h.
Constructor & Destructor Documentation
Uart::Uart ()
Definition at line 5 of file uart.cpp.
References bInitialize, fd, param_UART_FILE, and Serial_Open().
{
    tcflush(fd, TCIOFLUSH);
    bInitialize = Serial_Open(param_UART_FILE, B9600);
}
Uart::~Uart ()
Definition at line 11 of file uart.cpp.
References Serial_Close().
{
    Serial_Close();
}
Member Function Documentation
bool Uart::Serial_Close () protected
Definition at line 61 of file uart.cpp.
References fd.
Referenced by ~Uart().
{
        if(close (fd) < 0)
        {
            return false;
                }
                else
            return true;
}
bool Uart::Serial_Open (const char * serial_Name, speed_t baudrate) protected
Definition at line 16 of file uart.cpp.
References fd.
Referenced by Uart().
{
    struct termios serCfg;
        memset(&serCfg, 0, sizeof(serCfg));
    if((fd = open(serial_Name, O_RDWR | O_NOCTTY | O_NDELAY )) < 0) {
        printf("Failed to open serial port");
        return false;
        }
    else if(tcgetattr(fd, &serCfg) != 0) {
            printf("Failed to get configuration");
            return false;
    }
        cfsetispeed(&serCfg, baudrate);
        cfsetospeed(&serCfg, baudrate);
        cfmakeraw(&serCfg);
    if(tcsetattr(fd, TCSANOW, &serCfg) != 0) {
        printf("Failed to set configuration");
        return false;
        }
    return true;
}
int Uart::Serial_Read (char * buff, int len) protected
Definition at line 51 of file uart.cpp.
References bInitialize, and fd.
Referenced by ZigBee::ConfigZigBee(), and ZigBee::receive().
{
    if(bInitialize) {
        return read(fd, buff, len);
    }
    else {
        return -1;
    }
}
int Uart::Serial_Send (char * string, int len) protected
Definition at line 41 of file uart.cpp.
References bInitialize, and fd.
Referenced by ZigBee::ConfigZigBee(), and ZigBee::SendCommand().
{
    if(bInitialize) {
        return write(fd, string,len);
    }
    else {
        return -1;
    }
}
Member Data Documentation
bool Uart::bInitialize
Definition at line 28 of file uart.h.
Referenced by QBase::QBase(), Serial_Read(), Serial_Send(), Uart(), and ZigBee::ZigBee().
char Uart::cRecevBuff[12] protected
Definition at line 36 of file uart.h.
Referenced by ZigBee::ConfigZigBee().
char Uart::cSendBuff[12] protected
Definition at line 35 of file uart.h.
int Uart::fd private
Definition at line 39 of file uart.h.
Referenced by Serial_Close(), Serial_Open(), Serial_Read(), Serial_Send(), and Uart().
The documentation for this class was generated from the following files:
uart.h
uart.cpp