IHM Segment SOL: ZigBee Class Reference
ZigBee Class Reference
#include "zigbee.h"
Public Member Functions
ZigBee ()
void receive ()
void SendCommand ()
void SendConfig ()
Public Member Functions inherited from Uart
Uart ()
~Uart ()
Private Member Functions
bool ConfigZigBee ()
void decodeTrame ()
void GetConfigDrone (uint32_t *param)
void GetDroneError (droneError *param)
void GetDroneState (droneFltState *param)
void GetDroneTime (portTickType *param)
Private Attributes
QMessageBox MsgBox
int iIndexBufferIn
int iIndexBufferOut
bool bReadyToSend
Additional Inherited Members
Public Attributes inherited from Uart
bool bInitialize
Protected Member Functions inherited from Uart
bool Serial_Close ()
bool Serial_Open (const char *serial_Name, speed_t baudrate)
int Serial_Read (char *buff, int len)
int Serial_Send (char *string, int len)
Protected Attributes inherited from Uart
char cSendBuff [12]
char cRecevBuff [12]
Detailed Description
Definition at line 13 of file zigbee.h.
Constructor & Destructor Documentation
ZigBee::ZigBee () explicit
Definition at line 3 of file zigbee.cpp.
References Uart::bInitialize, bReadyToSend, ConfigZigBee(), DRN_ERR_NONE, and STATE_STARTING.
{
    if(bInitialize) {
        bInitialize = ConfigZigBee();
        st_CommandDrone.cTransX = 0;
        st_CommandDrone.cTransY = 0;
        st_CommandDrone.cTransZ = 0;
        st_CommandDrone.cRotZ = 0;
        st_DataIMU.xUpdateTime = 0;
        st_DataGPS.xUpdateTime = 0;
        st_DroneState.eErrorMask = DRN_ERR_NONE;
        st_DroneState.eFltState = STATE_STARTING;
        bReadyToSend = false;
    }
    else {
        //Erreur d'init UART
    }
}
Member Function Documentation
bool ZigBee::ConfigZigBee () private
Definition at line 23 of file zigbee.cpp.
References Uart::cRecevBuff, HISTORY_DEST_H, param_ADRESSE_DEST_H, param_ADRESSE_DEST_L, param_ADRESSE_EMET_H, param_ADRESSE_EMET_L, param_ENTRE_CONFIG, param_QUITE_CONFIG, Uart::Serial_Read(), and Uart::Serial_Send().
Referenced by ZigBee().
{
    Serial_Send(param_ENTRE_CONFIG, 3);
    Serial_Read(cRecevBuff, 2);      //Reçoit la confirmation
    if(cRecevBuff[0] != 'o' || cRecevBuff[1] != 'k') {
        return false;               //Si pas de confirmation, on quite
    }
    Serial_Send(param_ADRESSE_EMET_H, 4);             //Demande l'adresse de l'émetteur (MSBs)
    Serial_Read(cRecevBuff, 4);
    printf("adresse du module : %X %X %X %X ",cRecevBuff[0],cRecevBuff[1],cRecevBuff[2],cRecevBuff[3]);
    Serial_Send(param_ADRESSE_EMET_L, 4);             //Demande l'adresse de l'émetteur (LSBs)
    Serial_Read(cRecevBuff, 4);
    printf("%X %X %X %X\n",cRecevBuff[0],cRecevBuff[1],cRecevBuff[2],cRecevBuff[3]);
    Serial_Send(param_ADRESSE_DEST_H, 4);             //Demande l'adresse du recepteur (MSBs)
    Serial_Read(cRecevBuff, 4);
    if(strncmp(cRecevBuff, HISTORY_DEST_H, 4) != 0) {
//        return false;
        //Si différente, on tape dedans...
    }
    Serial_Send(param_ADRESSE_DEST_L, 4);             //Demande l'adresse du recepteur (LSBs)
    Serial_Read(cRecevBuff, 4);
    if(strncmp(cRecevBuff, HISTORY_DEST_H, 4) != 0) {
//        return false;
        //Si différente, on tape dedans...
    }
    Serial_Send(param_QUITE_CONFIG, 4);             //Quite la Config
    Serial_Read(cRecevBuff, 2);      //Reçoit la confirmation
    if(cRecevBuff[0] != 'o' || cRecevBuff[1] != 'k') {
        return false;               //Si pas de confirmation, on quite
    }
    return true;
}
void ZigBee::decodeTrame () private
Definition at line 128 of file zigbee.cpp.
References bReadyToSend, GetConfigDrone(), GetDroneError(), GetDroneState(), GetDroneTime(), iIndexBufferIn, PARAM_DRONE_CONFIG_ulCritBatteryLvl, PARAM_DRONE_CONFIG_ulCritObstacleDist, PARAM_DRONE_CONFIG_ulCritZigbeeSignalLvl, PARAM_DRONE_CONFIG_ulMaxAngle, PARAM_DRONE_CONFIG_ulMinAltitude, PARAM_DRONE_CONFIG_ulTakeoffAltitude, PARAM_DRONE_CONFIG_xBatteryMonitoringPeriod, PARAM_DRONE_CONFIG_xBatteryTimeout, PARAM_DRONE_CONFIG_xDetectObstaclePeriod, PARAM_DRONE_CONFIG_xFlightCtrlPeriod, PARAM_DRONE_CONFIG_xGPSReceivePeriod, PARAM_DRONE_CONFIG_xGPSTimeout, PARAM_DRONE_CONFIG_xIMUDataTimeout, PARAM_DRONE_CONFIG_xTelemeterTimeout, PARAM_DRONE_CONFIG_xVideoTogglePeriod, PARAM_DRONE_CONFIG_xZigbeeCmdTimeout, PARAM_DRONE_CONFIG_xZigbeeReceivePeriod, PARAM_DRONE_CONFIG_xZigbeeReceiveTimeout, PARAM_DRONE_ERROR, PARAM_FLY_STATE, PARAM_GPS_xUpdateTime, PARAM_IMU_xUpdateTime, and STATE_STARTING.
Referenced by receive().
{
    iIndexBufferIn = 0;
    for(int i = 0 ; i < st_BufferIn.lengthData ; i++) {
        switch(st_BufferIn.Data[iIndexBufferIn++]) {
        case PARAM_DRONE_CONFIG_ulMaxAngle:
            GetConfigDrone(&(st_droneConfig.ulMaxAngle));
            break;
        case PARAM_DRONE_CONFIG_ulTakeoffAltitude:
            GetConfigDrone(&(st_droneConfig.ulTakeoffAltitude));
            break;
        case PARAM_DRONE_CONFIG_ulMinAltitude:
            GetConfigDrone(&(st_droneConfig.ulMinAltitude));
            break;
        case PARAM_DRONE_CONFIG_ulCritBatteryLvl:
            GetConfigDrone(&(st_droneConfig.ulCritBatteryLvl));
            break;
        case PARAM_DRONE_CONFIG_ulCritObstacleDist:
            GetConfigDrone(&(st_droneConfig.ulCritObstacleDist));
            break;
        case PARAM_DRONE_CONFIG_ulCritZigbeeSignalLvl:
            GetConfigDrone(&(st_droneConfig.ulCritZigbeeSignalLvl));
            break;
        case PARAM_DRONE_CONFIG_xBatteryMonitoringPeriod:
            GetConfigDrone(&(st_droneConfig.xBatteryMonitoringPeriod));
            break;
        case PARAM_DRONE_CONFIG_xDetectObstaclePeriod:
            GetConfigDrone(&(st_droneConfig.xDetectObstaclePeriod));
            break;
        case PARAM_DRONE_CONFIG_xZigbeeReceivePeriod:
            GetConfigDrone(&(st_droneConfig.xZigbeeReceivePeriod));
            break;
        case PARAM_DRONE_CONFIG_xFlightCtrlPeriod:
            GetConfigDrone(&(st_droneConfig.xFlightCtrlPeriod));
            break;
        case PARAM_DRONE_CONFIG_xGPSReceivePeriod:
            GetConfigDrone(&(st_droneConfig.xGPSReceivePeriod));
            break;
        case PARAM_DRONE_CONFIG_xVideoTogglePeriod:
            GetConfigDrone(&(st_droneConfig.xVideoTogglePeriod));
            break;
        case PARAM_DRONE_CONFIG_xIMUDataTimeout:
            st_droneConfig.xIMUDataTimeout = st_BufferIn.Data[iIndexBufferIn++];
            break;
        case PARAM_DRONE_CONFIG_xZigbeeCmdTimeout:
            st_droneConfig.xZigbeeCmdTimeout = st_BufferIn.Data[iIndexBufferIn++];
            break;
        case PARAM_DRONE_CONFIG_xZigbeeReceiveTimeout:
            st_droneConfig.xZigbeeReceiveTimeout = st_BufferIn.Data[iIndexBufferIn++];
            break;
        case PARAM_DRONE_CONFIG_xTelemeterTimeout:
            st_droneConfig.xTelemeterTimeout = st_BufferIn.Data[iIndexBufferIn++];
            break;
        case PARAM_DRONE_CONFIG_xBatteryTimeout:
            st_droneConfig.xBatteryTimeout = st_BufferIn.Data[iIndexBufferIn++];
            break;
        case PARAM_DRONE_CONFIG_xGPSTimeout:
            st_droneConfig.xGPSTimeout = st_BufferIn.Data[iIndexBufferIn++];
            //printf("\n%d\n",st_droneConfig.xGPSTimeout);
            break;
        case PARAM_DRONE_ERROR:
            GetDroneError(&(st_DroneState.eErrorMask));
            //ERREUR A TRAITER?
            //Ici, si erreur mineur-> on demande si elle doit être ignoré
                                   // et on stock pour la prochaine émission
            break;
        case PARAM_FLY_STATE:
            GetDroneState(&(st_DroneState.eFltState));
            if(st_DroneState.eFltState == STATE_STARTING)
                bReadyToSend = false;
            break;
        case PARAM_IMU_xUpdateTime:
            GetDroneTime(&(st_DataIMU.xUpdateTime));
            break;
        case PARAM_GPS_xUpdateTime:
            GetDroneTime(&(st_DataGPS.xUpdateTime));
            break;
        default:
            break;
        }
    }
}
void ZigBee::GetConfigDrone (uint32_t * param) private
Definition at line 214 of file zigbee.cpp.
References iIndexBufferIn.
Referenced by decodeTrame().
{
    *param = 0;
    for(int j = 0 ; j < 4 ; j++)
        *param = (uint32_t)( (*param)*256 + (uint32_t)st_BufferIn.Data[ (3-j) + iIndexBufferIn ] );
    iIndexBufferIn += 4;
}
void ZigBee::GetDroneError (droneError * param) private
Definition at line 223 of file zigbee.cpp.
References iIndexBufferIn.
Referenced by decodeTrame().
{
    *param = (droneError)0;
    for(int j = 0 ; j < 2 ; j++)
        *param = (droneError)( (*param)*256 + (droneError)st_BufferIn.Data[ (1-j) + iIndexBufferIn ] );
    iIndexBufferIn += 2;
}
void ZigBee::GetDroneState (droneFltState * param) private
Definition at line 232 of file zigbee.cpp.
References iIndexBufferIn.
Referenced by decodeTrame().
{
    *param = (droneFltState)st_BufferIn.Data[iIndexBufferIn++];
}
void ZigBee::GetDroneTime (portTickType * param) private
Definition at line 237 of file zigbee.cpp.
References iIndexBufferIn.
Referenced by decodeTrame().
{
    *param = 0;
    for(int j = 0 ; j < 4 ; j++)
        *param = (portTickType)( (*param)*256 + (portTickType)st_BufferIn.Data[ (3-j) + iIndexBufferIn ] );
    iIndexBufferIn += 4;
}
void ZigBee::receive ()
Definition at line 74 of file zigbee.cpp.
References bReadyToSend, decodeTrame(), and Uart::Serial_Read().
Referenced by QBase::run().
{
    if( (st_BufferIn.lengthData = (char)Serial_Read(st_BufferIn.Data, 95)) < 0) {// !! SA ASSURER QU'IL PEUT LIRE MOINS DE 95 OCTETS
        return;
    }
    if(st_BufferIn.lengthData == 0) {
        printf("HELLO\n");
        return;
    }
    bReadyToSend = true;
    decodeTrame();
}
void ZigBee::SendCommand ()
Definition at line 88 of file zigbee.cpp.
References bReadyToSend, CMD_GET_STATUS, iIndexBufferOut, PARAM_CMD_DRONE, PARAM_CMD_ID, and Uart::Serial_Send().
Referenced by QBase::run().
{
    /* Envoit les infos Commandes au drone
     * Et demande de retourner son status
     */
    if(bReadyToSend) {
        iIndexBufferOut = 0;
        st_BufferOut.lengthData = 0;
        st_BufferOut.Data[iIndexBufferOut++] = (char)(PARAM_CMD_DRONE);
        st_BufferOut.Data[iIndexBufferOut++] = (char)(st_CommandDrone.cTransX);
        st_BufferOut.Data[iIndexBufferOut++] = (char)(st_CommandDrone.cTransY);
        st_BufferOut.Data[iIndexBufferOut++] = (char)(st_CommandDrone.cTransZ);
        st_BufferOut.Data[iIndexBufferOut++] = (char)(st_CommandDrone.cRotZ);
        st_BufferOut.lengthData++;
        st_BufferOut.Data[iIndexBufferOut++] = (char)(PARAM_CMD_ID);
        st_BufferOut.Data[iIndexBufferOut++] = (char)(CMD_GET_STATUS);
        st_BufferOut.lengthData++;
        char *tmp = (char*)malloc((size_t)(iIndexBufferOut+1));
        tmp[0] = st_BufferOut.lengthData;
        memcpy(&tmp[1],st_BufferOut.Data, iIndexBufferOut);
        if(Serial_Send(tmp, iIndexBufferOut+1 ) < 0) {
            //ERREUR D'ECRITURE!!
        }
        free(tmp);
        bReadyToSend = false;
    }
}
void ZigBee::SendConfig ()
Definition at line 123 of file zigbee.cpp.
References bReadyToSend.
{
    bReadyToSend = false;
}
Member Data Documentation
bool ZigBee::bReadyToSend private
Definition at line 39 of file zigbee.h.
Referenced by decodeTrame(), receive(), SendCommand(), SendConfig(), and ZigBee().
int ZigBee::iIndexBufferIn private
Definition at line 37 of file zigbee.h.
Referenced by decodeTrame(), GetConfigDrone(), GetDroneError(), GetDroneState(), and GetDroneTime().
int ZigBee::iIndexBufferOut private
Definition at line 38 of file zigbee.h.
Referenced by SendCommand().
QMessageBox ZigBee::MsgBox private
Definition at line 34 of file zigbee.h.
The documentation for this class was generated from the following files:
zigbee.h
zigbee.cpp