IHM Segment SOL: slippymap.cpp File Reference
slippymap.cpp File Reference
#include <math.h>
#include <QtGui>
#include <QtNetwork>
#include "slippymap.h"
Macros
#define M_PI 3.14159265358979323846
Functions
uint qHash (const QPoint &p)
QPointF tileForCoordinate (qreal lat, qreal lng, int zoom)
qreal longitudeFromTile (qreal tx, int zoom)
qreal latitudeFromTile (qreal ty, int zoom)
Variables
const int tdim = 256
Macro Definition Documentation
#define M_PI 3.14159265358979323846
Definition at line 7 of file slippymap.cpp.
Referenced by latitudeFromTile(), and tileForCoordinate().
Function Documentation
qreal latitudeFromTile (qreal ty, int zoom)
Definition at line 34 of file slippymap.cpp.
References M_PI.
Referenced by SlippyMap::pan().
{
    qreal zn = static_cast<qreal>(1 << zoom);
    qreal n = M_PI - 2 * M_PI * ty / zn;
    qreal lng = 180.0 / M_PI * atan(0.5 * (exp(n) - exp(-n)));
    return lng;
}
qreal longitudeFromTile (qreal tx, int zoom)
Definition at line 27 of file slippymap.cpp.
Referenced by SlippyMap::pan().
{
    qreal zn = static_cast<qreal>(1 << zoom);
    qreal lat = tx / zn * 360.0 - 180.0;
    return lat;
}
uint qHash (const QPoint & p)
Definition at line 10 of file slippymap.cpp.
{
    return p.x() * 17 ^ p.y();
}
QPointF tileForCoordinate (qreal lat, qreal lng, int zoom)
Definition at line 18 of file slippymap.cpp.
References M_PI.
Referenced by SlippyMap::invalidate(), SlippyMap::pan(), and SlippyMap::render().
{
    qreal zn = static_cast<qreal>(1 << zoom);
    qreal tx = (lng + 180.0) / 360.0;
    qreal ty = (1.0 - log(tan(lat * M_PI / 180.0) +
                          1.0 / cos(lat * M_PI / 180.0)) / M_PI) / 2.0;
    return QPointF(tx * zn, ty * zn);
}
Variable Documentation
const int tdim = 256
Definition at line 16 of file slippymap.cpp.
Referenced by SlippyMap::invalidate(), SlippyMap::pan(), SlippyMap::SlippyMap(), and SlippyMap::tileRect().